BEGIN;

ALTER TABLE backtest_runs
  ADD COLUMN IF NOT EXISTS portfolio_long_bars_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS portfolio_short_bars_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS portfolio_flat_bars_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS portfolio_long_return_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS portfolio_short_return_pct NUMERIC(12, 4) NOT NULL DEFAULT 0;

ALTER TABLE backtest_symbol_results
  ADD COLUMN IF NOT EXISTS long_bars_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS short_bars_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flat_bars_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS long_return_pct NUMERIC(12, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS short_return_pct NUMERIC(12, 4) NOT NULL DEFAULT 0;

COMMIT;
