export type MarketCapWatchlistEntry = {
  symbol: string;
  rank: number;
  marketCapUsd: number;
};

const FALLBACK_TOP_100_USDT_SYMBOLS = [
  "BTCUSDT",
  "ETHUSDT",
  "XRPUSDT",
  "BNBUSDT",
  "SOLUSDT",
  "DOGEUSDT",
  "ADAUSDT",
  "TRXUSDT",
  "AVAXUSDT",
  "SHIBUSDT",
  "DOTUSDT",
  "LINKUSDT",
  "TONUSDT",
  "SUIUSDT",
  "LTCUSDT",
  "BCHUSDT",
  "XLMUSDT",
  "HBARUSDT",
  "UNIUSDT",
  "PEPEUSDT",
  "APTUSDT",
  "NEARUSDT",
  "ICPUSDT",
  "ETCUSDT",
  "FILUSDT",
  "RENDERUSDT",
  "ATOMUSDT",
  "ARBUSDT",
  "OPUSDT",
  "INJUSDT",
  "TAOUSDT",
  "VETUSDT",
  "ALGOUSDT",
  "KASUSDT",
  "XMRUSDT",
  "MNTUSDT",
  "CROUSDT",
  "IMXUSDT",
  "STXUSDT",
  "FETUSDT",
  "TIAUSDT",
  "GRTUSDT",
  "MKRUSDT",
  "THETAUSDT",
  "BGBUSDT",
  "XDCUSDT",
  "LDOUSDT",
  "AAVEUSDT",
  "SANDUSDT",
  "MANAUSDT",
  "FLOWUSDT",
  "EGLDUSDT",
  "NEOUSDT",
  "EOSUSDT",
  "IOTAUSDT",
  "KAVAUSDT",
  "RUNEUSDT",
  "GALAUSDT",
  "PENDLEUSDT",
  "QNTUSDT",
  "PYTHUSDT",
  "FTMUSDT",
  "JUPUSDT",
  "SEIUSDT",
  "WIFUSDT",
  "BONKUSDT",
  "DYDXUSDT",
  "COMPUSDT",
  "CRVUSDT",
  "SNXUSDT",
  "1INCHUSDT",
  "ZECUSDT",
  "DASHUSDT",
  "ENJUSDT",
  "CHZUSDT",
  "ROSEUSDT",
  "KLAYUSDT",
  "RVNUSDT",
  "GMTUSDT",
  "CELOUSDT",
  "ANKRUSDT",
  "OCEANUSDT",
  "BATUSDT",
  "ZILUSDT",
  "HOTUSDT",
  "MASKUSDT",
  "CFXUSDT",
  "NEXOUSDT",
  "RSRUSDT",
  "GLMUSDT",
  "QTUMUSDT",
  "MINAUSDT",
  "YFIUSDT",
  "WOOUSDT",
  "BLURUSDT",
  "STRKUSDT",
  "ACHUSDT",
  "ZRXUSDT",
  "ONDOUSDT",
  "OMUSDT",
] as const;

export const buildFallbackMarketCapWatchlist = (limit = 100): MarketCapWatchlistEntry[] => {
  const max = Math.max(1, Math.min(limit, FALLBACK_TOP_100_USDT_SYMBOLS.length));
  return FALLBACK_TOP_100_USDT_SYMBOLS.slice(0, max).map((symbol, index) => {
    const rank = index + 1;
    const syntheticCap = 1_250_000_000_000 / Math.pow(rank, 0.78);
    return {
      symbol,
      rank,
      marketCapUsd: Number(syntheticCap.toFixed(2)),
    };
  });
};

